name: PluginTemplate
main: template.PluginTemplate
version: 1.0.0
author: <your name>
team: <your team, optional>
description: "Plugin Template"
license: MIT
website: https://github.com/paulevsGitch/RisingWorldPluginTemplate